package com.example.demo;

public class StrutturaDati {
	
	//attributi
	/**
	 * 
	 */
	
String PROGRAMMA;
String ASSE;
String LINEA;
String AZIONE;
String TITOLO_DEL_PROGETTO;
String AMBITO_INTERVENTO;
String SETTORE;
String DATA_DI_AVVIO;
String DURATA_DEL_PROGETTO;
String COSTO_COMPLESSIVO;
String CONTRIBUTO_SPESE_RICHIESTO;
String CONTRIBUTO_TOTALE_AMMESSO;
String CONTRIBUTO_INVEST_RICHIESTO;
String CONTRIBUTO_INVEST_AMMESSO;
String CONTRIBUTO_INVEST_CONCESSO_PROVVISORIO;
String COFINANZIAMENTO_INVEST_BENEFICIARIO2;
String CONTRIBUTO_SPESE_RICHIESTO2;
String CONTRIBUTO_SPESE_AMMESSO1;
String CONTRIBUTO_SPESE_CONCESSO_PROVVISORIO;
String BENEFICIARIO;
String CODICE_ATECO;
String PROVINCIA;
String LOCALIZZAZIONE_INVESTIMENTO;
String CODICE_ISTAT;
String SITO_WEB;
String DESCRIZIONE_PROGETTO;
String REVOCA;
public String getPROGRAMMA() {
	return PROGRAMMA;
}
public void setPROGRAMMA(String pROGRAMMA) {
	PROGRAMMA = pROGRAMMA;
}
public String getASSE() {
	return ASSE;
}
public void setASSE(String aSSE) {
	ASSE = aSSE;
}
public String getLINEA() {
	return LINEA;
}
public void setLINEA(String lINEA) {
	LINEA = lINEA;
}
public String getAZIONE() {
	return AZIONE;
}
public void setAZIONE(String aZIONE) {
	AZIONE = aZIONE;
}
public String getTITOLO_DEL_PROGETTO() {
	return TITOLO_DEL_PROGETTO;
}
public void setTITOLO_DEL_PROGETTO(String tITOLO_DEL_PROGETTO) {
	TITOLO_DEL_PROGETTO = tITOLO_DEL_PROGETTO;
}
public String getAMBITO_INTERVENTO() {
	return AMBITO_INTERVENTO;
}
public void setAMBITO_INTERVENTO(String aMBITO_INTERVENTO) {
	AMBITO_INTERVENTO = aMBITO_INTERVENTO;
}
public String getSETTORE() {
	return SETTORE;
}
public void setSETTORE(String sETTORE) {
	SETTORE = sETTORE;
}
public String getDATA_DI_AVVIO() {
	return DATA_DI_AVVIO;
}
public void setDATA_DI_AVVIO(String dATA_DI_AVVIO) {
	DATA_DI_AVVIO = dATA_DI_AVVIO;
}
public String getDURATA_DEL_PROGETTO() {
	return DURATA_DEL_PROGETTO;
}
public void setDURATA_DEL_PROGETTO(String dURATA_DEL_PROGETTO) {
	DURATA_DEL_PROGETTO = dURATA_DEL_PROGETTO;
}
public String getCOSTO_COMPLESSIVO() {
	return COSTO_COMPLESSIVO;
}
public void setCOSTO_COMPLESSIVO(String cOSTO_COMPLESSIVO) {
	COSTO_COMPLESSIVO = cOSTO_COMPLESSIVO;
}
public String getCONTRIBUTO_SPESE_RICHIESTO() {
	return CONTRIBUTO_SPESE_RICHIESTO;
}
public void setCONTRIBUTO_SPESE_RICHIESTO(String cONTRIBUTO_SPESE_RICHIESTO) {
	CONTRIBUTO_SPESE_RICHIESTO = cONTRIBUTO_SPESE_RICHIESTO;
}
public String getCONTRIBUTO_TOTALE_AMMESSO() {
	return CONTRIBUTO_TOTALE_AMMESSO;
}
public void setCONTRIBUTO_TOTALE_AMMESSO(String cONTRIBUTO_TOTALE_AMMESSO) {
	CONTRIBUTO_TOTALE_AMMESSO = cONTRIBUTO_TOTALE_AMMESSO;
}
public String getCONTRIBUTO_INVEST_RICHIESTO() {
	return CONTRIBUTO_INVEST_RICHIESTO;
}
public void setCONTRIBUTO_INVEST_RICHIESTO(String cONTRIBUTO_INVEST_RICHIESTO) {
	CONTRIBUTO_INVEST_RICHIESTO = cONTRIBUTO_INVEST_RICHIESTO;
}
public String getCONTRIBUTO_INVEST_AMMESSO() {
	return CONTRIBUTO_INVEST_AMMESSO;
}
public void setCONTRIBUTO_INVEST_AMMESSO(String cONTRIBUTO_INVEST_AMMESSO) {
	CONTRIBUTO_INVEST_AMMESSO = cONTRIBUTO_INVEST_AMMESSO;
}
public String getCONTRIBUTO_INVEST_CONCESSO_PROVVISORIO() {
	return CONTRIBUTO_INVEST_CONCESSO_PROVVISORIO;
}
public void setCONTRIBUTO_INVEST_CONCESSO_PROVVISORIO(String cONTRIBUTO_INVEST_CONCESSO_PROVVISORIO) {
	CONTRIBUTO_INVEST_CONCESSO_PROVVISORIO = cONTRIBUTO_INVEST_CONCESSO_PROVVISORIO;
}
public String getCOFINANZIAMENTO_INVEST_BENEFICIARIO2() {
	return COFINANZIAMENTO_INVEST_BENEFICIARIO2;
}
public void setCOFINANZIAMENTO_INVEST_BENEFICIARIO2(String cOFINANZIAMENTO_INVEST_BENEFICIARIO2) {
	COFINANZIAMENTO_INVEST_BENEFICIARIO2 = cOFINANZIAMENTO_INVEST_BENEFICIARIO2;
}
public String getCONTRIBUTO_SPESE_RICHIESTO2() {
	return CONTRIBUTO_SPESE_RICHIESTO2;
}
public void setCONTRIBUTO_SPESE_RICHIESTO2(String cONTRIBUTO_SPESE_RICHIESTO2) {
	CONTRIBUTO_SPESE_RICHIESTO2 = cONTRIBUTO_SPESE_RICHIESTO2;
}
public String getCONTRIBUTO_SPESE_AMMESSO1() {
	return CONTRIBUTO_SPESE_AMMESSO1;
}
public void setCONTRIBUTO_SPESE_AMMESSO1(String cONTRIBUTO_SPESE_AMMESSO1) {
	CONTRIBUTO_SPESE_AMMESSO1 = cONTRIBUTO_SPESE_AMMESSO1;
}
public String getCONTRIBUTO_SPESE_CONCESSO_PROVVISORIO() {
	return CONTRIBUTO_SPESE_CONCESSO_PROVVISORIO;
}
public void setCONTRIBUTO_SPESE_CONCESSO_PROVVISORIO(String cONTRIBUTO_SPESE_CONCESSO_PROVVISORIO) {
	CONTRIBUTO_SPESE_CONCESSO_PROVVISORIO = cONTRIBUTO_SPESE_CONCESSO_PROVVISORIO;
}
public String getBENEFICIARIO() {
	return BENEFICIARIO;
}
public void setBENEFICIARIO(String bENEFICIARIO) {
	BENEFICIARIO = bENEFICIARIO;
}
public String getCODICE_ATECO() {
	return CODICE_ATECO;
}
public void setCODICE_ATECO(String cODICE_ATECO) {
	CODICE_ATECO = cODICE_ATECO;
}
public String getPROVINCIA() {
	return PROVINCIA;
}
public void setPROVINCIA(String pROVINCIA) {
	PROVINCIA = pROVINCIA;
}
public String getLOCALIZZAZIONE_INVESTIMENTO() {
	return LOCALIZZAZIONE_INVESTIMENTO;
}
public void setLOCALIZZAZIONE_INVESTIMENTO(String lOCALIZZAZIONE_INVESTIMENTO) {
	LOCALIZZAZIONE_INVESTIMENTO = lOCALIZZAZIONE_INVESTIMENTO;
}
public String getCODICE_ISTAT() {
	return CODICE_ISTAT;
}
public void setCODICE_ISTAT(String cODICE_ISTAT) {
	CODICE_ISTAT = cODICE_ISTAT;
}
public String getSITO_WEB() {
	return SITO_WEB;
}
public void setSITO_WEB(String sITO_WEB) {
	SITO_WEB = sITO_WEB;
}
public String getDESCRIZIONE_PROGETTO() {
	return DESCRIZIONE_PROGETTO;
}
public void setDESCRIZIONE_PROGETTO(String dESCRIZIONE_PROGETTO) {
	DESCRIZIONE_PROGETTO = dESCRIZIONE_PROGETTO;
}
public String getREVOCA() {
	return REVOCA;
}
public void setREVOCA(String rEVOCA) {
	REVOCA = rEVOCA;
}
/**
 * 
 * @param pROGRAMMA nome programma dell'impresa
 * @param aSSE
 * @param lINEA
 * @param aZIONE
 * @param tITOLO_DEL_PROGETTO
 * @param aMBITO_INTERVENTO
 * @param sETTORE
 * @param dATA_DI_AVVIO
 * @param dURATA_DEL_PROGETTO
 * @param cOSTO_COMPLESSIVO
 * @param cONTRIBUTO_SPESE_RICHIESTO
 * @param cONTRIBUTO_TOTALE_AMMESSO
 * @param cONTRIBUTO_INVEST_RICHIESTO
 * @param cONTRIBUTO_INVEST_AMMESSO
 * @param cONTRIBUTO_INVEST_CONCESSO_PROVVISORIO
 * @param cOFINANZIAMENTO_INVEST_BENEFICIARIO2
 * @param cONTRIBUTO_SPESE_RICHIESTO2
 * @param cONTRIBUTO_SPESE_AMMESSO1
 * @param cONTRIBUTO_SPESE_CONCESSO_PROVVISORIO
 * @param bENEFICIARIO
 * @param cODICE_ATECO
 * @param pROVINCIA
 * @param lOCALIZZAZIONE_INVESTIMENTO
 * @param cODICE_ISTAT
 * @param sITO_WEB
 * @param dESCRIZIONE_PROGETTO
 * @param rEVOCA
 */
public StrutturaDati(String pROGRAMMA, String aSSE, String lINEA, String aZIONE, String tITOLO_DEL_PROGETTO,
		String aMBITO_INTERVENTO, String sETTORE, String dATA_DI_AVVIO, String dURATA_DEL_PROGETTO,
		String cOSTO_COMPLESSIVO, String cONTRIBUTO_SPESE_RICHIESTO, String cONTRIBUTO_TOTALE_AMMESSO,
		String cONTRIBUTO_INVEST_RICHIESTO, String cONTRIBUTO_INVEST_AMMESSO,
		String cONTRIBUTO_INVEST_CONCESSO_PROVVISORIO, String cOFINANZIAMENTO_INVEST_BENEFICIARIO2,
		String cONTRIBUTO_SPESE_RICHIESTO2, String cONTRIBUTO_SPESE_AMMESSO1,
		String cONTRIBUTO_SPESE_CONCESSO_PROVVISORIO, String bENEFICIARIO, String cODICE_ATECO, String pROVINCIA,
		String lOCALIZZAZIONE_INVESTIMENTO, String cODICE_ISTAT, String sITO_WEB, String dESCRIZIONE_PROGETTO,
		String rEVOCA) {
	super();
	PROGRAMMA = pROGRAMMA;
	ASSE = aSSE;
	LINEA = lINEA;
	AZIONE = aZIONE;
	TITOLO_DEL_PROGETTO = tITOLO_DEL_PROGETTO;
	AMBITO_INTERVENTO = aMBITO_INTERVENTO;
	SETTORE = sETTORE;
	DATA_DI_AVVIO = dATA_DI_AVVIO;
	DURATA_DEL_PROGETTO = dURATA_DEL_PROGETTO;
	COSTO_COMPLESSIVO = cOSTO_COMPLESSIVO;
	CONTRIBUTO_SPESE_RICHIESTO = cONTRIBUTO_SPESE_RICHIESTO;
	CONTRIBUTO_TOTALE_AMMESSO = cONTRIBUTO_TOTALE_AMMESSO;
	CONTRIBUTO_INVEST_RICHIESTO = cONTRIBUTO_INVEST_RICHIESTO;
	CONTRIBUTO_INVEST_AMMESSO = cONTRIBUTO_INVEST_AMMESSO;
	CONTRIBUTO_INVEST_CONCESSO_PROVVISORIO = cONTRIBUTO_INVEST_CONCESSO_PROVVISORIO;
	COFINANZIAMENTO_INVEST_BENEFICIARIO2 = cOFINANZIAMENTO_INVEST_BENEFICIARIO2;
	CONTRIBUTO_SPESE_RICHIESTO2 = cONTRIBUTO_SPESE_RICHIESTO2;
	CONTRIBUTO_SPESE_AMMESSO1 = cONTRIBUTO_SPESE_AMMESSO1;
	CONTRIBUTO_SPESE_CONCESSO_PROVVISORIO = cONTRIBUTO_SPESE_CONCESSO_PROVVISORIO;
	BENEFICIARIO = bENEFICIARIO;
	CODICE_ATECO = cODICE_ATECO;
	PROVINCIA = pROVINCIA;
	LOCALIZZAZIONE_INVESTIMENTO = lOCALIZZAZIONE_INVESTIMENTO;
	CODICE_ISTAT = cODICE_ISTAT;
	SITO_WEB = sITO_WEB;
	DESCRIZIONE_PROGETTO = dESCRIZIONE_PROGETTO;
	REVOCA = rEVOCA;
}
}